version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
        SPRING_DATA_MONGODB_URI: "mongodb+srv://osder:78575353@cluster0.jdqqlsg.mongodb.net/vet_cristo?retryWrites=true&w=majority&appName=Cluster0"
        SPRING_PROFILES_ACTIVE: production
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
